/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package crime1;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Prabhu
 */
public class complaintRECORDS extends javax.swing.JFrame {

    /**
     * Creates new form complaintRECORDS
     */
      private static Connection con;
 private ResultSet r;
    public complaintRECORDS() throws ClassNotFoundException {
        initComponents();
        con=DB.getConn();
    }
    public ResultSet getCrimeID(int crime_id ) throws SQLException
{

try
{

	//step 3: create a stement reference using Connection interface createStatement() method
	PreparedStatement stmt=con.prepareStatement("select * from Complaint where crime_id=?");

	//procedure call

	//CallableStatement stmt=con.prepareCall("{call getAuthorById(?)}");

stmt.setInt(1,crime_id);
	r=stmt.executeQuery();



}
catch(SQLException exe1)
		{

			throw exe1;
	}

return r;
}
       public ResultSet deleteComplaint(int crime_id)throws SQLException
{
try
{
		//int rowAfftected=0;
		PreparedStatement stmt=con.prepareStatement("delete from  Complaint where crime_id=?");
		//try(CallableStatement stmt=con.prepareCall("{call deleteAuthors(?)}");)
		{

			stmt.setInt(1,crime_id);



			r=stmt.executeQuery();
		}
}
		catch(SQLException exe1)
				{

					throw exe1;
			}
return r;
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        NAME = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Address = new javax.swing.JTextArea();
        number = new javax.swing.JTextField();
        mail_id = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        comp_desc = new javax.swing.JTextArea();
        time = new javax.swing.JTextField();
        location = new javax.swing.JTextField();
        comp_type = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        crime_id = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel2.setText(" Complaints");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 10, 240, 40);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 255));
        jLabel3.setText(" Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(200, 120, 190, 30);

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 255));
        jLabel4.setText("  Address");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(180, 160, 220, 30);

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 255));
        jLabel5.setText("Mobile Number");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(190, 210, 180, 30);

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 255, 255));
        jLabel6.setText("Mail_Id");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(190, 260, 80, 30);

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 255, 255));
        jLabel7.setText("Complaint Type");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(190, 310, 180, 30);

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 255, 255));
        jLabel8.setText("Complaint Description");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(190, 370, 250, 20);

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 255, 255));
        jLabel9.setText("Time Of Crime");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(190, 420, 170, 20);

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 255, 255));
        jLabel10.setText("Date Of Crime");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(190, 450, 180, 30);

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 255, 255));
        jLabel11.setText("Crime location");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(190, 490, 170, 30);

        NAME.setEditable(false);
        NAME.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        NAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAMEActionPerformed(evt);
            }
        });
        jPanel1.add(NAME);
        NAME.setBounds(480, 120, 280, 30);

        Address.setEditable(false);
        Address.setColumns(20);
        Address.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        Address.setRows(5);
        jScrollPane1.setViewportView(Address);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(480, 160, 280, 30);

        number.setEditable(false);
        number.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberActionPerformed(evt);
            }
        });
        jPanel1.add(number);
        number.setBounds(480, 210, 280, 30);

        mail_id.setEditable(false);
        mail_id.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        mail_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mail_idActionPerformed(evt);
            }
        });
        jPanel1.add(mail_id);
        mail_id.setBounds(480, 260, 280, 30);

        date.setEditable(false);
        date.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });
        jPanel1.add(date);
        date.setBounds(480, 450, 280, 30);

        comp_desc.setEditable(false);
        comp_desc.setColumns(20);
        comp_desc.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        comp_desc.setRows(5);
        jScrollPane2.setViewportView(comp_desc);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(480, 360, 280, 40);

        time.setEditable(false);
        time.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeActionPerformed(evt);
            }
        });
        jPanel1.add(time);
        time.setBounds(480, 410, 280, 30);

        location.setEditable(false);
        location.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationActionPerformed(evt);
            }
        });
        jPanel1.add(location);
        location.setBounds(480, 490, 280, 30);

        comp_type.setEditable(false);
        comp_type.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        comp_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comp_typeActionPerformed(evt);
            }
        });
        jPanel1.add(comp_type);
        comp_type.setBounds(480, 310, 280, 30);

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel12.setText("Crime_Id");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(910, 90, 150, 30);

        crime_id.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jPanel1.add(crime_id);
        crime_id.setBounds(910, 120, 280, 30);

        jButton1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton1.setText("GET_INFO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(820, 650, 120, 30);

        jButton3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 0, 0));
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(660, 650, 90, 29);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel13.setText("-");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel13);
        jLabel13.setBounds(1230, 10, 21, 30);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 0, 0));
        jButton4.setText("WITHDRAW COMPLAINT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(20, 620, 340, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crime1/crime-virtual-set.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1380, 820);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1380, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAMEActionPerformed

    private void numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberActionPerformed

    private void mail_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mail_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mail_idActionPerformed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    private void timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeActionPerformed

    private void locationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try
		{
		java.sql.ResultSet r=getCrimeID(Integer.parseInt(crime_id.getText().toString().trim()));
                                                                                //returns the current  selected item

		if(r.next())
		{
			NAME.setText(r.getString(1));
			Address.setText(r.getString(2));
                        number.setText(r.getString(3));
                        mail_id.setText(r.getString(4));
                        comp_type.setText(r.getString(5));
                        comp_desc.setText(r.getString(6));
                        time.setText(r.getString(7));
                        date.setText(r.getString(8));
                        location.setText(r.getString(9));
                        crime_id.setText(r.getString(10));
			//t4.setText(r.getString(4));

			//t1.setEnabled(false);
			NAME.setEnabled(false);
			Address.setEnabled(false);
                        number.setEnabled(false);
                        mail_id.setEnabled(false);
                        comp_type.setEnabled(false);
                        comp_desc.setEnabled(false);
                        time.setEnabled(false);
                        date.setEnabled(false);
                        location.setEnabled(false);
                       // t2.setText("");
					//t3.setText("");
		//t4.setText("");
		}
	}
	catch(java.sql.SQLException exe1)
				{

					JOptionPane.showMessageDialog(null,"Failed to Retrieve the Data......");

					exe1.printStackTrace();
		}// TODO add your handling code here:
  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        this.setState(JFrame.ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseClicked

    private void comp_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comp_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comp_typeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
CrimeReport r= new CrimeReport();
 r.pack();
 r.setVisible(true);
            r.setLocationRelativeTo(null);
            r.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
try{
        java.sql.ResultSet r=deleteComplaint(Integer.parseInt(crime_id.getText().toString().trim()));
        JOptionPane.showMessageDialog(null,"FIR Details deleted Successfully......");
        	
			//FIR_ID.setText("");
        NAME.setText(r.getString(1));
			Address.setText("");
                        number.setText("");
                        mail_id.setText("");
                        comp_type.setText("");
                        comp_desc.setText("");
                        time.setText("");
                        date.setText("");
                        location.setText("");
                        crime_id.setText("");
					
                
        
        }
        catch(java.sql.SQLException exe1){
            JOptionPane.showMessageDialog(null,"FIR DETIALS failed to deleted......");
        }        // TODO add your handling code here:
         // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(complaintRECORDS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(complaintRECORDS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(complaintRECORDS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(complaintRECORDS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new complaintRECORDS().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(complaintRECORDS.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Address;
    private javax.swing.JTextField NAME;
    private javax.swing.JTextArea comp_desc;
    private javax.swing.JTextField comp_type;
    private javax.swing.JTextField crime_id;
    private javax.swing.JTextField date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField location;
    private javax.swing.JTextField mail_id;
    private javax.swing.JTextField number;
    private javax.swing.JTextField time;
    // End of variables declaration//GEN-END:variables
}
