/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package crime1;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Prabhu
 */
public class CriminalsDetials extends javax.swing.JFrame {

    /**
     * Creates new form CriminalsDetials
     */
    private static Connection con=null;
	private ResultSet r;
    public CriminalsDetials() throws ClassNotFoundException {
        initComponents();
        con=DB.getConn();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Criminal_Id = new javax.swing.JTextField();
        Criminal_name = new javax.swing.JTextField();
        Criminal_crime_id = new javax.swing.JTextField();
        Criminal_mobile = new javax.swing.JTextField();
        No_of_crimes = new javax.swing.JTextField();
        Criminal_Address = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Criminal_Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(600, 130, 280, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Criminal_Id");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(620, 70, 220, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Criminal_Crime_id");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(550, 220, 340, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Criminal_mobile");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(570, 280, 330, 44);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("No of Crimes");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(620, 350, 250, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Criminal_Address");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(560, 420, 330, 30);
        jPanel1.add(Criminal_Id);
        Criminal_Id.setBounds(900, 70, 230, 30);
        jPanel1.add(Criminal_name);
        Criminal_name.setBounds(900, 140, 210, 30);

        Criminal_crime_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Criminal_crime_idActionPerformed(evt);
            }
        });
        jPanel1.add(Criminal_crime_id);
        Criminal_crime_id.setBounds(910, 220, 200, 30);

        Criminal_mobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Criminal_mobileActionPerformed(evt);
            }
        });
        jPanel1.add(Criminal_mobile);
        Criminal_mobile.setBounds(910, 290, 200, 30);

        No_of_crimes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                No_of_crimesActionPerformed(evt);
            }
        });
        jPanel1.add(No_of_crimes);
        No_of_crimes.setBounds(920, 350, 190, 30);
        jPanel1.add(Criminal_Address);
        Criminal_Address.setBounds(920, 420, 210, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setText("Back");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8);
        jLabel8.setBounds(964, 10, 90, 44);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("-");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9);
        jLabel9.setBounds(1060, 20, 30, 29);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1050, 510, 90, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Cancle");
        jPanel1.add(jButton2);
        jButton2.setBounds(920, 510, 100, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crime1/police_record.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -10, 1190, 640);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1193, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void insertCriminal()throws SQLException
{
    try
    {
        PreparedStatement stmt=con.prepareStatement("insert into Criminal (Criminal_id,criminal_name,criminal_crime_id,criminal_mobile,No_of_crimes,criminal_address) values(?,?,?,?,?,?)");
stmt.setString(1,Criminal_Id.getText());
stmt.setString(2,Criminal_name.getText());
stmt.setString(3,Criminal_crime_id.getText());
stmt.setString(4,Criminal_mobile.getText());
stmt.setString(5,No_of_crimes.getText());
stmt.setString(6,Criminal_Address.getText());
stmt.execute();

    }
    catch(Exception e)
    {
        JOptionPane.showMessageDialog(null,e);
    }
    
    
}
    private void Criminal_mobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Criminal_mobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Criminal_mobileActionPerformed

    private void No_of_crimesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_No_of_crimesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_No_of_crimesActionPerformed

    private void Criminal_crime_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Criminal_crime_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Criminal_crime_idActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED); 
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
         HOME h=new HOME();
        h.setVisible(true);
            h.pack();
            h.setLocationRelativeTo(null);
            h.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try{
        insertCriminal(); 
}
catch(Exception e)
{
}// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriminalsDetials.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriminalsDetials.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriminalsDetials.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriminalsDetials.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CriminalsDetials().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(CriminalsDetials.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Criminal_Address;
    private javax.swing.JTextField Criminal_Id;
    private javax.swing.JTextField Criminal_crime_id;
    private javax.swing.JTextField Criminal_mobile;
    private javax.swing.JTextField Criminal_name;
    private javax.swing.JTextField No_of_crimes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
