/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package crime1;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Prabhu
 */
public class CriminalREC extends javax.swing.JFrame {

    /**
     * Creates new form CriminalREC
     */
    private static Connection con;
 private ResultSet r;
    public CriminalREC() {
        initComponents();
        try {
            con=DB.getConn();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CriminalREC.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public ResultSet getCrimeID(int Criminal_Id ) throws SQLException
{

try
{

	//step 3: create a stement reference using Connection interface createStatement() method
	PreparedStatement stmt=con.prepareStatement("select * from Criminal where Criminal_id=?");

	//procedure call

	//CallableStatement stmt=con.prepareCall("{call getAuthorById(?)}");

stmt.setInt(1,Criminal_Id);
	r=stmt.executeQuery();



}
catch(SQLException exe1)
		{

			throw exe1;
	}

return r;
}
    public ResultSet deleteCriminal(int Criminal_Id)throws SQLException
{
try
{
		//int rowAfftected=0;
		PreparedStatement stmt=con.prepareStatement("delete from  Criminal where Criminal_id=?");
		//try(CallableStatement stmt=con.prepareCall("{call deleteAuthors(?)}");)
		{

			stmt.setInt(1,Criminal_Id);



			r=stmt.executeQuery();
		}
}
		catch(SQLException exe1)
				{

					throw exe1;
			}
return r;
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Criminal_Id = new javax.swing.JTextField();
        Criminal_name = new javax.swing.JTextField();
        Criminal_crime_id = new javax.swing.JTextField();
        Criminal_mobile = new javax.swing.JTextField();
        No_of_crimes = new javax.swing.JTextField();
        Criminal_Address = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Criminal_Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(320, 180, 280, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Criminal_Id");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(320, 110, 220, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Criminal_Crime_id");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(320, 240, 340, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Criminal_mobile");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(320, 300, 330, 44);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("No of Crimes");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(320, 370, 250, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Criminal_Address");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(320, 460, 330, 30);

        Criminal_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Criminal_IdActionPerformed(evt);
            }
        });
        jPanel1.add(Criminal_Id);
        Criminal_Id.setBounds(780, 120, 290, 30);
        jPanel1.add(Criminal_name);
        Criminal_name.setBounds(780, 180, 300, 40);

        Criminal_crime_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Criminal_crime_idActionPerformed(evt);
            }
        });
        jPanel1.add(Criminal_crime_id);
        Criminal_crime_id.setBounds(780, 250, 300, 30);

        Criminal_mobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Criminal_mobileActionPerformed(evt);
            }
        });
        jPanel1.add(Criminal_mobile);
        Criminal_mobile.setBounds(780, 320, 300, 30);

        No_of_crimes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                No_of_crimesActionPerformed(evt);
            }
        });
        jPanel1.add(No_of_crimes);
        No_of_crimes.setBounds(780, 390, 300, 30);
        jPanel1.add(Criminal_Address);
        Criminal_Address.setBounds(780, 460, 300, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("-");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9);
        jLabel9.setBounds(1220, 10, 30, 58);

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel10.setText("CRIMINAL RECORDS");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 20, 330, 50);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("GET_INFO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1050, 540, 140, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(920, 540, 100, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 0, 0));
        jButton3.setText("REMOVE\n DETIALS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(20, 590, 260, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crime1/crime-virtual-set.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1330, 680);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1325, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Criminal_crime_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Criminal_crime_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Criminal_crime_idActionPerformed

    private void Criminal_mobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Criminal_mobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Criminal_mobileActionPerformed

    private void No_of_crimesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_No_of_crimesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_No_of_crimesActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void Criminal_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Criminal_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Criminal_IdActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
CrimeReport h=new CrimeReport();
        h.setVisible(true);
        h.pack();
        h.setLocationRelativeTo(null);
        h.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
		{
		java.sql.ResultSet r=getCrimeID(Integer.parseInt(Criminal_Id.getText().toString().trim()));
                                                                                //returns the current  selected item

		if(r.next())
		{
			Criminal_name.setText(r.getString(2));
			Criminal_crime_id.setText(r.getString(3));
                        Criminal_mobile.setText(r.getString(4));
                        No_of_crimes.setText(r.getString(5));
                        Criminal_Address.setText(r.getString(6));
                        
			//t4.setText(r.getString(4));

			//t1.setEnabled(false);
                        Criminal_name.setEnabled(false);
			Criminal_crime_id.setEnabled(false);
			Criminal_mobile.setEnabled(false);
                        No_of_crimes.setEnabled(false);
                        Criminal_Address.setEnabled(false);
                        
                       // t2.setText("");
					//t3.setText("");
		//t4.setText("");
		}
	}
	catch(java.sql.SQLException exe1)
				{

					JOptionPane.showMessageDialog(null,"Failed to Retrieve the Data......");

					exe1.printStackTrace();
		}// TODO add your handling code here:

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
try{
        java.sql.ResultSet r=deleteCriminal(Integer.parseInt(Criminal_Id.getText().toString().trim()));
        JOptionPane.showMessageDialog(null,"FIR Details deleted Successfully......");
        	
			//FIR_ID.setText("");
        Criminal_name.setText("");
			Criminal_crime_id.setText("");
                        Criminal_mobile.setText("");
                        No_of_crimes.setText("");
                        Criminal_Address.setText("");
                        		
                
        
        }
        catch(java.sql.SQLException exe1){
            JOptionPane.showMessageDialog(null,"FIR DETIALS failed to deleted......");
        }        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriminalREC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriminalREC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriminalREC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriminalREC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriminalREC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Criminal_Address;
    private javax.swing.JTextField Criminal_Id;
    private javax.swing.JTextField Criminal_crime_id;
    private javax.swing.JTextField Criminal_mobile;
    private javax.swing.JTextField Criminal_name;
    private javax.swing.JTextField No_of_crimes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
